### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by seanc** [Athora190/final-project#19]
The Navbar should use Appbar material UI component. If you need a reference check out:
https://github.com/JustDame/Team2-Assignment-8-Now-With-Pages/blob/master/src/components/Navbar/index.js
https://github.com/JustDame/Team2-Assignment-8-Now-With-Pages/blob/master/src/components/Navbar/NavbarMenu.js

Should have links to Survey page, Saved Recipes page, and when the user is logged out Sign in and Register pages but when they are logged in Logout

The Sign in, Register, and Logout displaying on a specific condition can be implemented with a test property because the backend does not have functionality for that yet.

**Comment by Jordane-Allen** [comment]
Nav Bar is complete and functional
